services:
  # PostgreSQL Database for Keycloak
  postgres:
    image: postgres:15-alpine
    container_name: orion-postgres-dev
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    
    ports:
      - "5432:5432"
    
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    
    networks:
      - orion-network
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Keycloak Service
  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    container_name: orion-keycloak-dev
    environment:
      # Database configuration
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres123
      
      # Keycloak admin credentials
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
      
      # Keycloak configuration for development
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HTTP_ENABLED: true
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      KC_LOG_LEVEL: DEBUG
    
    ports:
      - "8080:8080"
    
    volumes:
      - keycloak_dev_data:/opt/keycloak/data
    
    command: ["start-dev"]
    
    depends_on:
      postgres:
        condition: service_healthy
    
    networks:
      - orion-network
    
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/8080 && echo -e 'GET /health/ready HTTP/1.1\\r\\nhost: 127.0.0.1:8080\\r\\nConnection: close\\r\\n\\r\\n' >&3 && cat <&3 | grep -q '200 OK'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s

  # Frontend Development Server (Hot Reload)
  frontend-dev:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: orion-frontend-dev
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - VITE_KEYCLOAK_URL=http://localhost:8080
      - VITE_KEYCLOAK_REALM=orion
      - VITE_KEYCLOAK_CLIENT_ID=orion-client
      - NODE_ENV=development
    depends_on:
      keycloak:
        condition: service_healthy
    networks:
      - orion-network
    restart: unless-stopped

volumes:
  postgres_dev_data:
    driver: local
  keycloak_dev_data:
    driver: local

networks:
  orion-network:
    driver: bridge
